runtime: python38
entrypoint: gunicorn -b :$PORT main:app
instance_class: F1

env_variables: 
  PORT: '8080'
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: 'Password'
  MYSQL_DB: 'cs411proj'
  MYSQL_HOST: '34.173.205.39'
  INSTANCE_CONNECTION_NAME: 'cs411demo:us-central1:cs411demo'

automatic_scaling:
  max_instances: 1

# handlers:

# - url: static/scripts